config/routes.rb
Rails.application.routes.draw do
  get "/articles", to: "articles#index", as: :articles
  get "/articles/new", to: "articles#new", as: :new_article
  post "/articles", to: "articles#create"
  get "/articles/:id", to: "articles#show", as: :article

  get "articles/:id/edit", to: "articles#edit", as: "edit_article"
  patch "articles/:id", to: "articles#update"

  delete "/articles/:id", to: "articles#destroy"

  # Login
  get "login", to: "sessions#new", as: :login
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy", as: :logout

  get "up" => "rails/health#show", as: :rails_health_check

  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :content
  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  enum :role, { unapproved: 1, admin: 10 }

  def self.[](username)
    find_by!(username: username)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  allow_browser versions: :modern

  private

  attr_reader :current_user

  def require_login
    redirect_to(login_url) unless current_user
  end

  def require_admin_user
    render_access_denied unless current_user&.admin?
  end

  def render_access_denied
    render(plain: "403 - Access denied", status: :forbidden, content_type: "text/html")
  end

  def authenticate_user
    return unless session[:user_id]

    @current_user = User.find(session[:user_id])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  before_action :authenticate_user
  before_action :require_login, only: %i[ new edit update destroy ]
  before_action :require_admin_user, only: %i[ new edit update destroy ]

  def index
    @articles = Article.all
  end

  def show; end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render :new, status: "uncompleted"
    end
  end

  def edit; end

  def update
    if @article.update(article_params)
       redirect_to @article
    else
      render :edit, status: "uncompleted"
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(role: :admin, username: session_params[:username])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id

      redirect_to(articles_path, notice: "Loggd in")
    else
      redirect_to(login_path, alert: "Login Failed")
    end
  end

  def destroy
    session[:user_id] = nil

    redirect_to(articles_path, notice: "Logged out")
  end

  private

  def session_params
    params.permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_form.html.erb
<div style="display: block;">
	<%= form_with model: @article do |f| %>
		<div>
			<%= f.text_field :title, class: "little-text-field", placeholder: "Title" %>
		</div>
		<div>
			<%= f.rich_text_area :content, class: "big-text-field", placeholder: "Content"%>
		</div>

		<div style= "margin: 10px;">
			<%= f.submit %>
		</div>
	<% end %>
</div>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/delete.html.erb
<h1>Articles#delete</h1>
<p>Find me in app/views/articles/delete.html.erb</p>

app/views/articles/edit.html.erb
<div>
 <div>
   <%= link_to "←", articles_path, style: "font-size: 40px;" %>
 </div>

	<div class="general-div">
		<div>
		  <h1>Edit Article</h1>
		</div>

		<div>
			<%= render "form" %>
		</div>
	</div>
</div>

app/views/articles/index.html.erb
<div style="display: block;">
	<div style="text-align: right; margin-bottom: 20px;">
		<% if !@current_user %>
			<%= button_to "login", login_path%>	
		<% else %>
			<div style="display: flex; justify-content: space-between;">
				<%= button_to "+ Add", new_article_path, method: :get %>
				<%= button_to "Logout", logout_path, method: :delete, confirm: "Are you sure you want to logout?" %>
			</div>
    <% end %>	
	</div>

	<div class="general-div">
		<h1>Personal Blog</h1>

		<% @articles.each do |article| %>
		<div style="display: flex; justify-content: space-between;">
			<h3><%= link_to article.title, article%><h4 style="color: gray;"><%= article.created_at.to_formatted_s(:short) %></h4></h3> 
		</div>
		<% end %>
	</div>
</div>

app/views/articles/new.html.erb
<div>
	<div>
 		<%= link_to "←", articles_path, style: "font-size: 40px;" %>
	</div>
	<div class="general-div">
		<div>
		  <h1>New Article</h1>
		</div>

		<div>
			<%= render "form" %>
		</div>
	</div>
</div>

app/views/articles/show.html.erb
<div>
  <div>
    <%= link_to "←", articles_path, style: "font-size: 40px;" %>
  </div>

  <div class="general-div">
    <div>
      <div>
      <h1><%= @article.title %></h1>
      <h3><%= @article.created_at.to_formatted_s(:short) %></h3>
    </div>
    
    <div>
      <div>
        <%= @article.content %>

        <% if @current_user %>
          <div style="display: flex;  justify-content: space-between; margin-top: 20px;">
            <div>
            <%= button_to "Delete", @article, method: :delete, data: {  turbo_confirm: "are u sure?"} %>
          </div>

          <div>
            <%= button_to "edit article", edit_article_path, method: :get %>
          </div>
          </div>
        <% end %> 
      </div>
    </div>
  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Personal Blog Web App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>